-- ========================================
-- 1) Crear tabla notes
-- ========================================

create table if not exists public.notes (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    default auth.uid()
    references auth.users(id)
    on delete cascade,

  title text not null,

  content text not null
    default '',

  created_at timestamptz not null
    default now()
);

-- ========================================
-- 2) Activar seguridad (RLS)
-- ========================================

alter table public.notes enable row level security;

-- ========================================
-- 3) Política única simple
-- El usuario solo puede gestionar sus datos
-- ========================================

create policy if not exists "Users manage their own notes"
on public.notes
for all
to authenticated
using (
  user_id = auth.uid()
)
with check (
  user_id = auth.uid()
);

-- ========================================
-- 4) Índice (mejora rendimiento)
-- ========================================

create index if not exists idx_notes_user_id
on public.notes(user_id);



-- ========================================
-- 5) Supabase → Authentication → Users → Add user

Email: user@demo.com
Password: 1234

-- ========================================